version: '2.18.1'
services:
  solr1:
    image: solr:9.0
    container_name: solr1
    ports:
      - "8983:8983"
    environment:
      - SOLR_JAVA_MEM=-Xms2g -Xmx2g
      - ZK_HOST=zoo1:2181,zoo2:2181
    networks:
      - solr_network
    depends_on:
      - zoo1
      - zoo2
    volumes:
      - ./data/managed-schema:/opt/solr/server/solr/configsets/_default/conf/managed-schema.xml
      - ./data/solrconfig.xml:/opt/solr/server/solr/configsets/_default/conf/solrconfig.xml
      - ~/e_drive/current-data-solr1:/var/solr
      
    cap_add:
      - NET_ADMIN
     
  solr2:
    image: solr:9.0
    container_name: solr2
    ports:
      - "8982:8983"
    environment:
      - SOLR_JAVA_MEM=-Xms2g -Xmx2g
      - ZK_HOST=zoo1:2181,zoo2:2181   
    networks:
      - solr_network
    depends_on:
      - zoo1
      - zoo2
    volumes:
      - ./data/managed-schema:/opt/solr/server/solr/configsets/_default/conf/managed-schema.xml
      - ./data/solrconfig.xml:/opt/solr/server/solr/configsets/_default/conf/solrconfig.xml
      - ~/e_drive/current-data-solr2:/var/solr
    cap_add:
      - NET_ADMIN
  
  zoo1:
    image: zookeeper:3.8
    container_name: zoo1
    restart: always
    hostname: zoo1
    ports:
      - 2181:2181
      - 7001:7000
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181
      ZOO_4LW_COMMANDS_WHITELIST: mntr, conf, ruok
      ZOO_CFG_EXTRA: "metricsProvider.className=org.apache.zookeeper.metrics.prometheus.PrometheusMetricsProvider metricsProvider.httpPort=7000 metricsProvider.exportJvmInfo=true"
    networks:
      - solr_network
    volumes:      
      - ~/e_drive/current-data-zoo1-data:/data
      - ~/e_drive/current-data-zoo1-datalog:/datalog
      - ~/e_drive/current-data-zoo1-log:/log
      - ~/e_drive/current-data-zoo1-logs:/logs
   

  zoo2:
    image: zookeeper:3.8
    container_name: zoo2
    restart: always
    hostname: zoo2
    ports:
      - 2182:2181
      - 7002:7000
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181
      ZOO_4LW_COMMANDS_WHITELIST: mntr, conf, ruok
      ZOO_CFG_EXTRA: "metricsProvider.className=org.apache.zookeeper.metrics.prometheus.PrometheusMetricsProvider metricsProvider.httpPort=7000 metricsProvider.exportJvmInfo=true"
    networks:
      - solr_network
    volumes:      
      - ~/e_drive/current-data-zoo2-data:/data
      - ~/e_drive/current-data-zoo2-datalog:/datalog
      - ~/e_drive/current-data-zoo2-log:/log
      - ~/e_drive/current-data-zoo2-logs:/logs
   
   

networks:
  solr_network:
    external: true
   